server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ironbox?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123
#  mvc:
#    static-path-pattern: /**
#    view:
#      suffix: .html
#      cache: false
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
mybatis:
  mapperLocations: classpath:mappers/*.xml

