server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ironbox?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123
mybatis:
  mapperLocations: classpath:mappers/*.xml
